#############################################################################
# Makefile for building: libGuibi.so.1.0.0
# Generated by qmake (3.1) (Qt 5.10.1)
# Project:  Guibi.pro
# Template: lib
# Command: /home/guibi/Qt/5.10.1/gcc_64/bin/qmake -o Makefile Guibi.pro -spec linux-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DGUIBI_LIBRARY -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I../../../Qt/5.10.1/gcc_64/include -I../../../Qt/5.10.1/gcc_64/include/QtWidgets -I../../../Qt/5.10.1/gcc_64/include/QtGui -I../../../Qt/5.10.1/gcc_64/include/QtCore -I. -isystem /usr/include/libdrm -I../../../Qt/5.10.1/gcc_64/mkspecs/linux-g++
QMAKE         = /home/guibi/Qt/5.10.1/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/guibi/Qt/5.10.1/gcc_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/guibi/Qt/5.10.1/gcc_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Guibi1.0.0
DISTDIR = /home/guibi/Documents/Qt/Guibi/.tmp/Guibi1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/guibi/Qt/5.10.1/gcc_64/lib -shared -Wl,-soname,libGuibi.so.1
LIBS          = $(SUBLIBS) -L/home/guibi/Qt/5.10.1/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = gbarretitre.cpp \
		gmessagebox.cpp moc_gbarretitre.cpp \
		moc_gmessagebox.cpp
OBJECTS       = gbarretitre.o \
		gmessagebox.o \
		moc_gbarretitre.o \
		moc_gmessagebox.o
DIST          = ../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/lex.prf \
		Guibi.pro guibi_global.h \
		gbarretitre.h \
		gmessagebox.h \
		guibi.h gbarretitre.cpp \
		gmessagebox.cpp
QMAKE_TARGET  = Guibi
DESTDIR       = 
TARGET        = libGuibi.so.1.0.0
TARGETA       = libGuibi.a
TARGET0       = libGuibi.so
TARGETD       = libGuibi.so.1.0.0
TARGET1       = libGuibi.so.1
TARGET2       = libGuibi.so.1.0


first: all
####### Build rules

$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	-$(DEL_FILE) $(TARGET) $(TARGET0) $(TARGET1) $(TARGET2)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-ln -s $(TARGET) $(TARGET0)
	-ln -s $(TARGET) $(TARGET1)
	-ln -s $(TARGET) $(TARGET2)



staticlib: $(TARGETA)

$(TARGETA):  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGETA) 
	$(AR) $(TARGETA) $(OBJECTS)

Makefile: Guibi.pro ../../../Qt/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf ../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_pre.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/linux.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/sanitize.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-base.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-unix.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/qconfig.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_functions.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_config.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/toolchain.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/default_pre.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/resolve_config.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/default_post.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/warn_on.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qt.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/resources.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/moc.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/uic.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/thread.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/qmake_use.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/file_copies.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/exceptions.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/yacc.prf \
		../../../Qt/5.10.1/gcc_64/mkspecs/features/lex.prf \
		Guibi.pro \
		../../../Qt/5.10.1/gcc_64/lib/libQt5Widgets.prl \
		../../../Qt/5.10.1/gcc_64/lib/libQt5Gui.prl \
		../../../Qt/5.10.1/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -o Makefile Guibi.pro -spec linux-g++
../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_pre.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/unix.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/linux.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/sanitize.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-base.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/common/g++-unix.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/qconfig.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_charts_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_egl_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_glx_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_input_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_kms_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediagsttools_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_functions.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/qt_config.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/linux-g++/qmake.conf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../../Qt/5.10.1/gcc_64/mkspecs/features/exclusive_builds.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/toolchain.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/default_pre.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/resolve_config.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/default_post.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/warn_on.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/qt.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/resources.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/moc.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/opengl.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/uic.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/unix/thread.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/qmake_use.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/file_copies.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/testcase_targets.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/exceptions.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/yacc.prf:
../../../Qt/5.10.1/gcc_64/mkspecs/features/lex.prf:
Guibi.pro:
../../../Qt/5.10.1/gcc_64/lib/libQt5Widgets.prl:
../../../Qt/5.10.1/gcc_64/lib/libQt5Gui.prl:
../../../Qt/5.10.1/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile Guibi.pro -spec linux-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../../Qt/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents guibi_global.h gbarretitre.h gmessagebox.h guibi.h $(DISTDIR)/
	$(COPY_FILE) --parents gbarretitre.cpp gmessagebox.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../../Qt/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -Wall -W -dM -E -o moc_predefs.h ../../../Qt/5.10.1/gcc_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_gbarretitre.cpp moc_gmessagebox.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_gbarretitre.cpp moc_gmessagebox.cpp
moc_gbarretitre.cpp: ../../../Qt/5.10.1/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QFrame \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QPoint \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QMouseEvent \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLayout \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QToolButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtoolbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLabel \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlabel.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QIcon \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QImage \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QRgb \
		guibi_global.h \
		gbarretitre.h \
		moc_predefs.h \
		../../../Qt/5.10.1/gcc_64/bin/moc
	/home/guibi/Qt/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/guibi/Qt/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/guibi/Documents/Qt/Guibi -I/home/guibi/Qt/5.10.1/gcc_64/include -I/home/guibi/Qt/5.10.1/gcc_64/include/QtWidgets -I/home/guibi/Qt/5.10.1/gcc_64/include/QtGui -I/home/guibi/Qt/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gbarretitre.h -o moc_gbarretitre.cpp

moc_gmessagebox.cpp: ../../../Qt/5.10.1/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QDialog \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QPushButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLayout \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLabel \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlabel.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QPixmap \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QMap \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QDesktopWidget \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QStyle \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qstyle.h \
		guibi_global.h \
		gbarretitre.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QFrame \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QPoint \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QMouseEvent \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QToolButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtoolbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QIcon \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QImage \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QRgb \
		gmessagebox.h \
		moc_predefs.h \
		../../../Qt/5.10.1/gcc_64/bin/moc
	/home/guibi/Qt/5.10.1/gcc_64/bin/moc $(DEFINES) --include ./moc_predefs.h -I/home/guibi/Qt/5.10.1/gcc_64/mkspecs/linux-g++ -I/home/guibi/Documents/Qt/Guibi -I/home/guibi/Qt/5.10.1/gcc_64/include -I/home/guibi/Qt/5.10.1/gcc_64/include/QtWidgets -I/home/guibi/Qt/5.10.1/gcc_64/include/QtGui -I/home/guibi/Qt/5.10.1/gcc_64/include/QtCore -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include gmessagebox.h -o moc_gmessagebox.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

gbarretitre.o: gbarretitre.cpp gbarretitre.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QFrame \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QPoint \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QMouseEvent \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLayout \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QToolButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtoolbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLabel \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlabel.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QIcon \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QImage \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QRgb \
		guibi_global.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gbarretitre.o gbarretitre.cpp

gmessagebox.o: gmessagebox.cpp gmessagebox.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QApplication \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgetsglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtguiglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobal.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig-bootstrapped.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qconfig.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtcore-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsystemdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qprocessordetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcompilerdetection.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtypeinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsysinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlogging.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qflags.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbasicatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qgenericatomic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qatomic_msvc.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qglobalstatic.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmutex.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnumeric.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qversiontagging.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtgui-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtwidgets-config.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstring.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qchar.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrefcount.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qnamespace.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qarraydata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringliteral.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringview.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringbuilder.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qalgorithms.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiterator.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhashfunctions.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpair.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qbytearraylist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringlist.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qregexp.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qstringmatcher.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcoreevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qscopedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmetatype.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvarlengtharray.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontainerfwd.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qobject_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qeventloop.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qpoint.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsize.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcursor.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qwidget.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmargins.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpaintdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qrect.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpalette.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qcolor.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgb.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qrgba64.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qbrush.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvector.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qmatrix.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpolygon.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qregion.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdatastream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qiodevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qline.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtransform.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpainterpath.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qimage.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixelformat.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qpixmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qshareddata.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qhash.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfont.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontmetrics.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qfontinfo.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qkeysequence.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qevent.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qvariant.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qmap.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qdebug.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qtextstream.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qlocale.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qset.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qcontiguouscache.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurl.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qurlquery.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfile.h \
		../../../Qt/5.10.1/gcc_64/include/QtCore/qfiledevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qvector2d.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qtouchdevice.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qguiapplication.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qinputmethod.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QDialog \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qdialog.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QPushButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qpushbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/qicon.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLayout \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qboxlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qgridlayout.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QLabel \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qlabel.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qframe.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QPixmap \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QMap \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QStringList \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QDesktopWidget \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QStyle \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qstyle.h \
		guibi_global.h \
		gbarretitre.h \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QFrame \
		../../../Qt/5.10.1/gcc_64/include/QtCore/QPoint \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QMouseEvent \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/QToolButton \
		../../../Qt/5.10.1/gcc_64/include/QtWidgets/qtoolbutton.h \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QIcon \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QImage \
		../../../Qt/5.10.1/gcc_64/include/QtGui/QRgb
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o gmessagebox.o gmessagebox.cpp

moc_gbarretitre.o: moc_gbarretitre.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gbarretitre.o moc_gbarretitre.cpp

moc_gmessagebox.o: moc_gmessagebox.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_gmessagebox.o moc_gmessagebox.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(QINSTALL_PROGRAM) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(STRIP) --strip-unneeded $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET0)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET1)
	-$(SYMLINK) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET2)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET0) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET1) 
	 -$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET2)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

